### ISSUE TITLE
Update your npm and yarn versions

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/natklok#19]
The `package-lock.json` has an old `lockfileVersion` (1). I think this might be because your npm versions are old. I would be happy if you could check your npm versions and update them if needed via

```
npm i -g npm@latest
```

You might also update your yarn versions.

**Comment by Nautman** [comment]
This is the warning I get when running `npm install`

```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
```

**Comment by Nautman** [comment]
You won't need to fix any code as the updated versions will fix any problems that arise.

To close this issue, simply install the latest NPM and yarn versions.

**Comment by Nautman** [comment]
I'm being serious! 😆 

You need to update it @charlesmaddock

Every time you push things your old version keeps automatically downgrading the `package-lock.json` file, which although it hasn't caused any problems yet, it might cause issues later. It also means that there is an unnecessary 33k line git difference for every PR.

**Comment by charlesmaddock** [comment]
Sorry for not seeing this earlier! Fixed for me now.
