### ISSUE TITLE
Choose either Yarn or NPM

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/natklok#20]
Currently, you both have `yarn.lock` and `package-lock.json`. It is wise to choose only one package manager as you might run into some difficult bugs otherwise. I recommend you choose `yarn` but it is up to you :)

**Comment by Nautman** [comment]
For more information: https://stackoverflow.com/questions/49589493/is-there-any-harm-in-using-npm-and-yarn-in-the-same-project

**Comment by charlesmaddock** [comment]
@sakerhetspolisen what do you think? I think npm simply because I'm more used to it

**Comment by charlesmaddock** [comment]
Can we use npm? @sakerhetspolisen @Nautman

**Comment by sakerhetspolisen** [comment]
npm is fine for me

**Comment by sakerhetspolisen** [comment]
@charlesmaddock npm works for me!

**Comment by Nautman** [comment]
I recommend yarn because it comes with some nifty features but is also faster.

However, the choice is up to you. There are two PR's open. Choose one of them! 

Yarn: #46

NPM: #47

**Comment by sakerhetspolisen** [comment]
Well, I personally use yarn more, but it doesn't matter really. Merge one of them @charlesmaddock !

**Comment by charlesmaddock** [comment]
Ok, let's go with yarn!

**Comment by charlesmaddock** [comment]
Since these branches are quite old at this point, would it be OK if i removed the two branches you made @Nautman and simply begun and make a new yarn one?

**Comment by Nautman** [comment]
There is no need to make a new branch, since I've merged the master branch into the `yarn` branch. You can simply merge #46

**Comment by sakerhetspolisen** [comment]
Fixed in final-update-v1
