### ISSUE TITLE
Farming stars 

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/natklok#55]
If pressing the return button(tillbaka till start) after receiving some points but before pressing next question the question can be answered again which gives another star. Expected behavior is that if you press return and then go back to quiz the correct summary should load.

**Comment by Zigolox** [comment]
4 stars from the first question 
![image](https://user-images.githubusercontent.com/41542666/137625209-681ff8bc-e583-4f0c-9211-5c57388c6517.png)

**Comment by charlesmaddock** [comment]
Fixed this now in the coming final-update-v1 branch
