### ISSUE TITLE
Add Digital Ungdom logo

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/natklok#59]
Right now we only have a text with a link. We should instead use an Anna icon. The normal one should be fine.
![image](https://user-images.githubusercontent.com/41542666/138474267-a270ff07-3249-4c52-9215-14a3b0b29b7b.png)

**Comment by charlesmaddock** [comment]
This feels like an issue that will be open for a while, only taking up space. I'd like to close this unless you have a suggestion on how to un-curse the Anna icon haha. 

Maybe increase it's size? Or is the problem the icon itself?

**Comment by Zigolox** [comment]
The problem is that we only use the contour logo. I think i would work better with a full color one.

**Comment by sakerhetspolisen** [comment]
Yoo guys how about the animated logo we never implemented https://github.com/digitalungdom-se/infrarays.se/pull/44#issuecomment-797764721, and to the right of it a simple Digital ungdom text?

**Comment by Zigolox** [comment]
Would be very cool!! If it doesn't fit there we can also use it at some other place otherwise so please try to implement it if you have time.

**Comment by sakerhetspolisen** [comment]
Fixed in latest commit!

**Comment by Zigolox** [comment]
I think the new logo is a big improvement, especially the text, but I think it is a bit weird to have 3 different Anna emojis besides each other regularly. I think we instead should have only the regular one but a little bit larger.

**Comment by sakerhetspolisen** [comment]
Fixed in merged PR #106 #107
