### ISSUE TITLE
Font not loading in on ssf hosted instance of natklok

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/natklok#63]
![image](https://user-images.githubusercontent.com/41542666/138479525-dc664ab9-7f9c-4ea9-9098-be3f36293941.png)
![image](https://user-images.githubusercontent.com/41542666/138479553-0350c6af-d90e-4e81-9116-da4024e5ca63.png)

**Comment by charlesmaddock** [comment]
Any idea what this could be due to @Zigolox?

**Comment by Zigolox** [comment]
The font appears to be blocked for my browser. Does it work for you?

**Comment by sakerhetspolisen** [comment]
Does this still not work @Zigolox? All fonts are hosted locally now.

**Comment by Zigolox** [comment]
It works now, will close
