### ISSUE TITLE
SSFs Kahoot

### ISSUE THREAD

**Issue by Zigolox** [digitalungdom-se/natklok#71]
![image](https://user-images.githubusercontent.com/41542666/139321350-77671e7c-01c4-48aa-82da-7ecdfda49b52.png)
![image](https://user-images.githubusercontent.com/41542666/139321397-92c8b350-047c-4fcf-a18b-30b85356825e.png)
![image](https://user-images.githubusercontent.com/41542666/139321470-fe26426d-06e6-42b2-b938-cb9ef2265d75.png)
![image](https://user-images.githubusercontent.com/41542666/139321555-6eefe90a-a3da-46f7-ba04-d9afeff2dddc.png)
![image](https://user-images.githubusercontent.com/41542666/139321600-4bf08322-2553-4b1b-be3f-3673ade7cefc.png)
![image](https://user-images.githubusercontent.com/41542666/139321645-806b207a-6748-424c-89b6-2f414cfce3b7.png)
![image](https://user-images.githubusercontent.com/41542666/139321711-bb05f8ea-67e2-4a7b-84d3-72ab2aa7feb0.png)
![image](https://user-images.githubusercontent.com/41542666/139321766-ff4603be-cd5b-4936-8200-aa281b9f7721.png)
![image](https://user-images.githubusercontent.com/41542666/139321830-51c93a79-d563-4d97-9c6d-c8a17e204507.png)
![image](https://user-images.githubusercontent.com/41542666/139321899-47d1f790-8352-43b4-abe8-00967812918e.png)
![image](https://user-images.githubusercontent.com/41542666/139322042-8bc2260f-e7b7-4d1b-9a03-211efffbb12a.png)
![image](https://user-images.githubusercontent.com/41542666/139322124-9800fa03-510e-4d36-9f66-908570e5276b.png)
![image](https://user-images.githubusercontent.com/41542666/139322180-05e739d4-c731-424d-857d-21e3d14e0bd8.png)
![image](https://user-images.githubusercontent.com/41542666/139322236-1e3f84e3-162d-40d2-9b5a-703366a23883.png)
![image](https://user-images.githubusercontent.com/41542666/139322317-d736cdfa-487b-45ad-b260-fabcd99d6822.png)
![image](https://user-images.githubusercontent.com/41542666/139322417-b8721ca3-bdfb-45fd-98ec-d1d112582694.png)
![image](https://user-images.githubusercontent.com/41542666/139322486-b2fcf08f-ad00-4dcc-9087-da9253e4f349.png)
![image](https://user-images.githubusercontent.com/41542666/139322541-2fdd2a52-e003-4d05-82db-fb423dd77de7.png)
![image](https://user-images.githubusercontent.com/41542666/139322611-3e166caa-7e95-4c24-ab00-150f23f577f1.png)
![image](https://user-images.githubusercontent.com/41542666/139322664-86c3fc5d-b24c-4c48-af51-6669eb89ab28.png)
![image](https://user-images.githubusercontent.com/41542666/139322729-43ad5d55-2c35-446a-9b3c-b37e0c498687.png)
![image](https://user-images.githubusercontent.com/41542666/139322755-a854b528-d8ef-4eef-a3c3-6f1e3f85884f.png)
![image](https://user-images.githubusercontent.com/41542666/139322816-4f5d1d7d-8202-4651-a972-7efc451683d0.png)

**Comment by charlesmaddock** [comment]
Awesome, used this now to create some final questions for the mvp. Closing this now, we can reopen it in the future if we need more questions.
