### ISSUE TITLE
Make stars icon react to float score

### ISSUE THREAD

**Issue by sakerhetspolisen** [digitalungdom-se/natklok#73]
Some questions add a float to the total player score, this should be reflected by the star icon as well. 

![image](https://user-images.githubusercontent.com/68159964/140170065-4afe5df8-958c-4cf3-a996-219649396cd9.png)

**Comment by charlesmaddock** [comment]
@sakerhetspolisen I think we should try to avoid float values and stick to ints since they represent "whole" stars. I spoke to Johan about this a while ago and we thought that would be the best. Is that OK with you?
